- name: Configure iptables rules
  tasks:
  - name: Allow specific ip on port 9100
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 9100
      source: 123.145.167.254
      jump: ACCEPT
    become: yes

   - name: Custom SSH port
    ansible.builtin.iptables:
      chain: INPUT
      destination_port: 37656
      jump: ACCEPT
    become: yes

   - name: Block any
    ansible.builtin.iptables:
      chain: INPUT
      jump: DROP
    become: yes
